- type: disease
  id: DiseaseFoodPoisoning
  name: disease-DiseaseFoodPoisoning-name
  desc: disease-DiseaseFoodPoisoning-desc
  symptoms:
  - symptom: SymptomEmoteGroan
    probability: 
      1: 0.1
      2: 0.2
  - symptom: SymptomEmoteMoan
    probability: 
      1: 0.1
      2: 0.2
  - symptom: SymptomVomiting

- type: disease
  id: DiseaseNarcolepsySyndrome
  name: disease-DiseaseNarcolepsySyndrome-name
  desc: disease-DiseaseNarcolepsySyndrome-desc
  symptoms:
  - symptom: SymptomNarcolepsy

- type: disease
  id: DiseaseAMIV
  name: disease-DiseaseAMIV-name
  desc: disease-DiseaseAMIV-desc
  symptoms:
  - symptom: SymptomMonkeyShout
  - symptom: SymptomGeneticDamage