- type: disease
  id: DiseaseFoodPoisoning
  name: disease-DiseaseFoodPoisoning-name
  desc: disease-DiseaseFoodPoisoning-desc
  spreadPath: [ NonContagious ]
  stageProb: 0.03
  stages: [60, 180]
  symptoms:
  - symptom: SymptomEmoteGroan
    stages: [1, 2]
    probability: 
      1: 0.1
      2: 0.2
  - symptom: SymptomEmoteMoan
    stages: [1, 2]
    probability: 
      1: 0.1
      2: 0.2
  - symptom: SymptomVomiting
    stages: [2]
  cureSteps:
  - !type:CureConditions
    cureChance: 0.05
    conditions:
    - !type:ReagentCondition
      reagent: Ipecac
      min: 1
  - !type:CureWait
    requiredTicks: 900
  - !type:CureBedrest
      bedrestChance: 0.00066 #Abysmally Low to have an average of 300 ticks before a heal if they sleep
      sleepMultiplier: 5

- type: disease
  id: DiseaseNarcolepsySyndrome
  name: disease-DiseaseNarcolepsySyndrome-name
  desc: disease-DiseaseNarcolepsySyndrome-desc
  spreadPath: [ NonContagious ]
  stages: [180]
  symptoms:
  - symptom: SymptomNarcolepsy
    stages: [1]
  cureSteps:
  - !type:CureConditions
    cureChance: 0.05
    conditions:
    - !type:ReagentCondition
      reagent: Haloperidol
      min: 1
  - !type:CureWait
    requiredTicks: 900
  - !type:CureBedrest
      bedrestChance: 0.00066 #Abysmally Low to have an average of 300 ticks before a heal if they sleep
      sleepMultiplier: 5

- type: disease
  id: DiseaseAMIV
  name: disease-DiseaseAMIV-name
  desc: disease-DiseaseAMIV-desc
  spreadPath: [ Contact ]
  contactInfect: 0.005
  contactDeposit: 0.05
  stages: [180, 120]
  symptoms:
  - symptom: SymptomMonkeyShout
    stages: [2]
  - symptom: SymptomGeneticDamage
    stages: [2]
  cureSteps:
  - !type:CureConditions
    conditions:
    - !type:ReagentCondition
      reagent: JuiceBanana
      min: 3
  - !type:CureWait
    requiredTicks: 900
  - !type:CureBedrest
      bedrestChance: 0.00066 #Abysmally Low to have an average of 300 ticks before a heal if they sleep
      sleepMultiplier: 5