- type: antag
  id: MaintsSlasher
  name: roles-antag-slasher-name
  antagonist: true
  setPreference: true
  objective: roles-antag-slasher-objective
  previewStartingGear: SpaceNinjaGear
  requirements:
  - !type:OverallPlaytimeRequirement #Far Horizons
    time: 7200 # 2 hours - Far Horizons
#  - !type:DepartmentTimeRequirement #Far Horizons
#    department: Security
#    time: 3h
  playTimeTracker: AntagSlasher

#Slasher Gear
- type: startingGear
  id: SlasherGear
  equipment:
    jumpsuit: CoolTanktopUniformSuit
    back: ClothingBackpackSatchelLeather
    mask: ClothingMaskSlasher
    outerClothing: ClothingOuterFlannelRed
    shoes: ClothingShoesBootsCargo
