using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Timing;
using Robust.Shared.Containers;
using Content.Shared._FarHorizons.PowerArmor;
using Content.Shared.Wires;
using Content.Shared.Power.Components;
using System.Linq;
using Content.Shared.Power.EntitySystems;
using Content.Shared.Damage.Systems;
using Content.Shared.Damage.Components;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using System.Numerics;

namespace Content.Client._FarHorizons.PowerArmor;

[GenerateTypedNameReferences]
public sealed partial class PowerArmorMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private SharedContainerSystem _container;
    private SharedBatterySystem _battery;
    private DamageableSystem _damageable;

    private EntityUid _entity;
    private readonly Dictionary<PowerArmorVisualLayers, EntityUid?> _parts = new();
    private readonly Dictionary<PowerArmorVisualLayers, PartControls> _partControls = new();
    private PartControls? _openDetails;
    private float _updateTimer;
    private readonly StyleBoxFlat _barBackground = new() { BackgroundColor = Color.Black };
    private readonly StyleBoxFlat _barForeground = new();
    public event Action<PowerArmorVisualLayers, NetEntity>? OnUninstallPart;
    private readonly record struct PartControls(
        Button PartButton,
        RichTextLabel PartButtonLabel,
        TextureRect PartButtonArrow,
        ProgressBar Bar,
        RichTextLabel Percent,
        BoxContainer Details,
        RichTextLabel Description,
        Button UninstallButton);

    public PowerArmorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _container = _entityManager.System<SharedContainerSystem>();
        _battery = _entityManager.System<SharedBatterySystem>();
        _damageable = _entityManager.System<DamageableSystem>();

        _parts = new()
        {
            [PowerArmorVisualLayers.Head] = null,
            [PowerArmorVisualLayers.Chest] = null,
            [PowerArmorVisualLayers.RArm] = null,
            [PowerArmorVisualLayers.LArm] = null,
            [PowerArmorVisualLayers.RLeg] = null,
            [PowerArmorVisualLayers.LLeg] = null,
        };

        var panelsByLayer = new Dictionary<PowerArmorVisualLayers, PanelContainer>
        {
            [PowerArmorVisualLayers.Head] = Head,
            [PowerArmorVisualLayers.Chest] = Chest,
            [PowerArmorVisualLayers.RArm] = RArm,
            [PowerArmorVisualLayers.LArm] = LArm,
            [PowerArmorVisualLayers.RLeg] = RLeg,
            [PowerArmorVisualLayers.LLeg] = LLeg,
        };

        foreach (var (layer, panel) in panelsByLayer)
        {
            var controls = GeneratePanel(panel);
            _partControls[layer] = controls;

            controls.PartButton.OnPressed += _ => ToggleContainer(_partControls[layer], _parts[layer]);
            controls.UninstallButton.OnPressed += _ =>
            {
                if (_parts[layer] is { } part)
                    OnUninstallPart?.Invoke(layer, _entityManager.GetNetEntity(part));
            };
        }
    }
    public void SetEntity(EntityUid entity) => _entity = entity;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateTimer -= args.DeltaSeconds;

        if (_updateTimer > 0)
            return;

        _updateTimer = 0.1f;
        UpdateWindow();
    }

    public void UpdateWindow()
    {
        if(_container.TryGetContainer(_entity, "cell_slot", out var cellSlot) 
        && cellSlot.ContainedEntities.Count != 0
        && _entityManager.TryGetComponent<BatteryComponent>(cellSlot.ContainedEntities.First(), out var battery))
        {
            var charge = (int)Math.Round(_battery.GetChargeLevel((cellSlot.ContainedEntities.First(), battery)) * 100f); 
            ChargePercent.Text = $"{charge}%";
            ChargeBar.Value = charge;
            _barForeground.BackgroundColor = Color.InterpolateBetween(Color.Red, Color.Green, charge / 100f);

            ChargeBar.BackgroundStyleBoxOverride = _barBackground;
            ChargeBar.ForegroundStyleBoxOverride = _barForeground;
            ChargePercent.ModulateSelfOverride = Color.White;
        }
        else
        {
            ChargeBar.Value = 0;
            ChargePercent.Text = "Power Cell Missing.";
            ChargePercent.ModulateSelfOverride = Color.Red;
        }

        if(_entityManager.TryGetComponent<WiresPanelComponent>(_entity, out var wirePanel))
        {
            PanelStatus.Text = wirePanel.Open ? "Open" : "Closed";
            PanelStatus.ModulateSelfOverride = wirePanel.Open ? Color.LimeGreen : Color.Red;
        }

        if (_entityManager.TryGetComponent<PowerArmorComponent>(_entity, out var paComp))
        {
            foreach (var layer in _parts.Keys.ToList())
                if (paComp.Parts.TryGetValue(layer, out var part)) _parts[layer] = part;

            if (_entityManager.EntityExists(paComp.OtherHalf) && _entityManager.TryGetComponent<PowerArmorComponent>(paComp.OtherHalf, out var paComp2))
                if (paComp2.Parts.TryGetValue(PowerArmorVisualLayers.Head, out var headPart)) _parts[PowerArmorVisualLayers.Head] = headPart;
        }

        foreach (var (layer, controls) in _partControls)
            UpdateParts(controls, _parts[layer]);
    }

    private void UpdateParts(PartControls controls, EntityUid? part)
    {
        if (part != null)
        {
            if (!_entityManager.TryGetComponent<PowerArmorPartComponent>(part.Value, out var papComp))
                return;

            if (_entityManager.TryGetComponent<MetaDataComponent>(part.Value, out var metaData))
            {
                controls.PartButtonLabel.Text = metaData.EntityName;
                controls.PartButton.Disabled = false;
                controls.Description.Text = metaData.EntityDescription;
            }
            else
            {
                controls.PartButton.Text = "Empty";
                controls.PartButton.Disabled = true;
            }

            if (_entityManager.TryGetComponent<DamageableComponent>(part.Value, out var damageComp))
            {
                var integrity = Math.Clamp((int) ((papComp.MaxIntegrity - _damageable.GetPositiveDamage((part.Value, damageComp)).GetTotal()) / papComp.MaxIntegrity * 100), 0, 100);
                controls.Bar.Value = integrity;
                _barForeground.BackgroundColor = Color.InterpolateBetween(Color.Red, Color.Green, integrity / 100f);

                controls.Bar.BackgroundStyleBoxOverride = _barBackground;
                controls.Bar.ForegroundStyleBoxOverride = _barForeground;

                controls.Bar.Visible = true;
                controls.Percent.Text = $"{integrity}%";
                controls.Percent.Visible = true;
            }
            else
            {
                controls.Bar.Visible = false;
                controls.Percent.Visible = false;
                controls.Bar.BackgroundStyleBoxOverride = _barBackground;
            }
        }
        else
        {
            controls.PartButtonLabel.Text = "Empty";
            controls.PartButton.Disabled = true;
            controls.Bar.Visible = false;
            controls.Percent.Visible = false;

            if (controls.Details.Visible)
                controls.Details.Visible = false;
            if (_openDetails == controls)
                _openDetails = null;
        }
    }

    private PartControls GeneratePanel(PanelContainer panel)
    {
        var MainBoxContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };

        var PartNameIntegrityBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Name = $"{panel.Name}Row",
            HorizontalExpand = true,
            SetHeight = 30
        };

        var PartTypeLabel = new RichTextLabel
        {
            Text = $"{panel.Name}: ",
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(60, 0)
        };

        PartNameIntegrityBox.AddChild(PartTypeLabel);

        var PartNameButton = new Button
        {
            StyleClasses = { "CrossButtonRed" },
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Center,
            MinWidth = 350
        };

        var PartNameBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalExpand = true
        };

        var PartNameArrow = new TextureRect
        {
            StyleClasses = new StyleClassCollection("ButtonSquare"),
            TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png",
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            SetSize = new Vector2(16, 16),
            Margin = new Thickness(0, 2, 4, 0)
        };
        PartNameBox.AddChild(PartNameArrow);

        var PartNameLabel = new RichTextLabel
        {
            Name = $"{panel.Name}Label",
            Text="Emtpty",
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Center
        };
        PartNameBox.AddChild(PartNameLabel);

        PartNameButton.AddChild(PartNameBox);
        PartNameIntegrityBox.AddChild(PartNameButton);

        var PartIntegrityControl = new Control
        {
            HorizontalExpand = true,
            Margin = new Thickness(5, 0, 5, 0)
        };

        var PartIntegrityBar = new ProgressBar
        {
            Name = $"{panel.Name}Bar",
            MinValue = 0,
            MaxValue = 100,
            Value = 50,
            SetHeight = 25
        };
        PartIntegrityControl.AddChild(PartIntegrityBar);

        var PartPercentLabel = new RichTextLabel
        {
            Name = $"{panel.Name}Percent",
            Text = "50%",
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(5, 0, 0, 0)
        };
        PartIntegrityControl.AddChild(PartPercentLabel);

        PartNameIntegrityBox.AddChild(PartIntegrityControl);
        MainBoxContainer.AddChild(PartNameIntegrityBox);

        var DetailsBox = new BoxContainer
        {
            Name = $"{panel.Name}Details",
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Visible = false,
            Margin = new Thickness(10, 5, 10, 5)
        };

        var DetailsDivider = new PanelContainer
        {
            StyleClasses = { "LowDivider" },
            SetHeight = 1,
            Margin = new Thickness(0, 0, 0, 5)
        };
        DetailsBox.AddChild(DetailsDivider);

        var DescriptionUninstallBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };

        var DescriptionLabel = new RichTextLabel
        {
            Name = $"{panel.Name}Description",
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(10, 0),
            MaxWidth = 400
        };
        DescriptionUninstallBox.AddChild(DescriptionLabel);

        var UninstallButton = new Button
        {
            Name = $"{panel.Name}UninstallButton",
            Text = "Uninstall",
            StyleClasses = { "CrossButtonRed" },
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(10,0, 0, 0)
        };
        DescriptionUninstallBox.AddChild(UninstallButton);

        DetailsBox.AddChild(DescriptionUninstallBox);
        MainBoxContainer.AddChild(DetailsBox);

        panel.AddChild(MainBoxContainer);

        return new PartControls(PartNameButton, PartNameLabel, PartNameArrow, PartIntegrityBar, PartPercentLabel, DetailsBox, DescriptionLabel, UninstallButton);
    }

    private void ToggleContainer(PartControls container, EntityUid? part)
    {
        if (part == null)
            return;

        if (_openDetails == container)
        {
            container.Details.Visible = false;
            container.PartButtonArrow.TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png"; 
            _openDetails = null;
            return;
        }

        if (_openDetails != null)
        {
            _openDetails.Value.Details.Visible  = false;
            _openDetails.Value.PartButtonArrow.TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png"; 
        }

        container.Details.Visible = true;
        container.PartButtonArrow.TexturePath = "/Textures/_FarHorizons/Interface/VerbIcons/group90.svg.192dpi.png";
        _openDetails = container;
    }
    }