using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Timing;
using Robust.Shared.Containers;
using Content.Shared._FarHorizons.PowerArmor;
using Content.Shared.Wires;
using Content.Shared.Power.Components;
using System.Linq;
using Content.Shared.Power.EntitySystems;

namespace Content.Client._FarHorizons.PowerArmor;

[GenerateTypedNameReferences]
public sealed partial class PowerArmorMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly SharedContainerSystem _container;
    private readonly SharedBatterySystem _battery;

    public EntityUid Entity;

    public PowerArmorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _container = _entityManager.System<SharedContainerSystem>();
        _battery = _entityManager.System<SharedBatterySystem>();
    }

    public void SetEntity(EntityUid entity) 
        => Entity = entity;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateWindow();
    }

    public void UpdateWindow()
    {
        if(_container.TryGetContainer(Entity, "cell_slot", out var cellSlot) 
        && cellSlot.ContainedEntities.Count != 0
        && _entityManager.TryGetComponent<BatteryComponent>(cellSlot.ContainedEntities.First(), out var battery))
        {
            var charge = (int)Math.Round(_battery.GetChargeLevel((cellSlot.ContainedEntities.First(), battery)) * 100f); 
            ChargePercent.Text = $"{charge}%";
            ChargeBar.Value = charge;
            ChargeBar.ModulateSelfOverride = Color.InterpolateBetween(Color.Red, Color.LimeGreen, charge / 100);
            ChargePercent.ModulateSelfOverride = Color.White;
        }
        else
        {
            ChargeBar.Value = 0;
            ChargePercent.Text = "Power Cell Missing.";
            ChargePercent.ModulateSelfOverride = Color.Red;
        }

        if(_entityManager.TryGetComponent<WiresPanelComponent>(Entity, out var wirePanel))
        {
            PanelStatus.Text = wirePanel.Open ? "Open" : "Closed";
            PanelStatus.ModulateSelfOverride = wirePanel.Open ? Color.LimeGreen : Color.Red;
        }
        

        if(_container.TryGetContainer(Entity, "toggleable-clothing", out var tcContainer))
        {
            foreach(var item in tcContainer.ContainedEntities)
            {
                if(_container.TryGetContainer(item, "parts", out var headContainer))
                {
                    foreach(var headItem in headContainer.ContainedEntities)
                    {
                        if (!_entityManager.TryGetComponent<PowerArmorPartComponent>(headItem, out var vmComp) 
                        || (!_entityManager.TryGetComponent<MetaDataComponent>(headItem, out var metadata)))
                            continue;

                        switch(vmComp.PartType)
                        {
                            case PowerArmorVisualLayers.Head:
                                HeadLabel.Text = metadata.EntityName;
                                break;
                        }
                    }
                }
            }
        }

        if(_container.TryGetContainer(Entity, "parts", out var container))
        {
            foreach(var item in container.ContainedEntities)
            {
                if (!_entityManager.TryGetComponent<PowerArmorPartComponent>(item, out var vmComp) 
                || (!_entityManager.TryGetComponent<MetaDataComponent>(item, out var metadata)))
                    continue;

                switch(vmComp.PartType)
                {
                    case PowerArmorVisualLayers.Chest:
                        ChestLabel.Text = metadata.EntityName;
                        break;
                    case PowerArmorVisualLayers.RArm:
                        RArmLabel.Text = metadata.EntityName;
                        break;
                    case PowerArmorVisualLayers.LArm:
                        LArmLabel.Text = metadata.EntityName;
                        break;
                    case PowerArmorVisualLayers.RLeg:
                        RLegLabel.Text = metadata.EntityName;
                        break;
                    case PowerArmorVisualLayers.LLeg:
                        LLegLabel.Text = metadata.EntityName;
                        break;
                    default:
                        break;
                }
            }
        }
    }

    private static T? TryGetAssignComp<T>(IEntityManager entSys, EntityUid ent, ref T? assign) where T : Component
    {
        if(!entSys.TryGetComponent<T>(ent, out var comp))
            return null;

        assign = comp;
        return comp;
    }
}