using System.Linq;
using System.Numerics;
using Content.Shared.Body;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FarHorizons.PowerArmor.UI;

[GenerateTypedNameReferences]
public sealed partial class PowerArmorStatusDisplay : Control
{
    private static readonly ProtoId<ShaderPrototype> _shaderProto = "LimbTargetting";
    private Dictionary<ProtoId<OrganCategoryPrototype>, ShaderInstance> _shaders = new();

    private bool _shaderInitialized =>
        _shaders.Count > 0;

    public Dictionary<ProtoId<OrganCategoryPrototype>, DrawLimb> DrawLimbs = new();
    public List<DrawLabel> DrawLabels = new();
    public Vector3 DefaultColor = new(1f, 1f, 1f);
    public Vector3 HighlightColor = new(0.55f, 0f, 0f);

    public Vector3 FullHealthColor = new(0f, 1f, 0f);
    public Vector3 DamagedHealthColor = new(1f, 0.65f, 0f);
    public Vector3 BadlyDamagedHealthColor = new(1f, 0f, 0f);

    public bool DrawDebugBoxes;

    public bool WithHealth;

    public Dictionary<ProtoId<OrganCategoryPrototype>, float> LimbDamage = new();

    public PowerArmorStatusDisplay() => 
        RobustXamlLoader.Load(this);

    public void InitShaders(IPrototypeManager protoMan)
    {
        var baseShader = protoMan.Index(_shaderProto).InstanceUnique();
        baseShader.SetParameter("outerColor", DefaultColor);
        if (WithHealth)
        {
            baseShader.SetParameter("innerFill", true);
            baseShader.SetParameter("innerColor", DefaultColor);
        }

        foreach (var key in DrawLimbs.Keys)
            _shaders[key] = baseShader.Duplicate();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        if (!_shaderInitialized) return;

        UpdateShaders();

        foreach (var (limb, draw) in DrawLimbs.Reverse())
        {
            if (WithHealth) continue;

            handle.UseShader(_shaders[limb]);

            foreach (var texture in draw.Textures)
                handle.DrawTextureRect(texture, UIBox2.FromDimensions(0, 0, Width * UIScale, Height * UIScale));

            handle.UseShader(null);

            if (!DrawDebugBoxes) continue;

            handle.DrawRect(
                new UIBox2(
                    new Vector2(draw.Area.Left * Width * UIScale, draw.Area.Top * Height * UIScale),
                    new Vector2(draw.Area.Right * Width * UIScale, draw.Area.Bottom * Height * UIScale)),
                    Color.Red, 
                    false
                );
        }

        foreach (var label in DrawLabels)
        {
            Vector2 pos = new(label.Position.X * Width * UIScale, label.Position.Y * Height * UIScale);
            Color col = new(DefaultColor.X, DefaultColor.Y, DefaultColor.Z);
            handle.DrawString(label.Font, pos, label.Text, col);
        }
    }

    private void UpdateShaders()
    {
        foreach (var (limb, shader) in _shaders)
        {
            var color = DefaultColor;
            if (WithHealth)
                color = HealthColor(limb);

            shader.SetParameter("outerColor", HighlightColor);
            if (!WithHealth)
            {
                shader.SetParameter("innerFill", true);
                shader.SetParameter("innerColor", HighlightColor);
            }
            else
                shader.SetParameter("innerColor", color);
        }
    }

    private Vector3 HealthColor(ProtoId<OrganCategoryPrototype> limb)
    {
        if (!LimbDamage.TryGetValue(limb, out var health))
            return DefaultColor;
        
        // Hardcoded shit :skull:
        if (health > 50)
            return BadlyDamagedHealthColor;
        if (health > 25)
            return DamagedHealthColor;

        return FullHealthColor;
    }
}